### ISSUE TITLE
digicampipe/digicampipe/tests/test_lid_ccd.py::test_find_stars FAILED

### ISSUE THREAD

**Issue by sagreus** [cta-sst-1m/digicampipe#88]
I went through the README: https://github.com/calispac/digicampipe/blob/master/README.md
And I got this error [error.txt](https://github.com/calispac/digicampipe/files/1646766/error.txt) when running the tests "pytest -vv digicampipe", which was solved after installing "astrometry.net"

**Comment by dneise** [comment]
Thanks for reporting this issue.

In principle astrometry.net should not be a dependency ... so in case one does not have astrometry.net, the system is supposed to fall back to a web service, but for this one needs an API key. 
Since you had neither, the tests did not work. 

Did you try the quick tests as well? `pytest -c quick_test.ini digicampipe` Did they work?

@yrenier What do you think? How should we solve this issue, I am sure more and more users will have the same issue.

**Comment by sagreus** [comment]
Yes, the quick test all passed except 2 that were SKIPPED:
digicampipe/tests/test_zfits_event_source.py::test_and_benchmark_simple_event_source SKIPPED                                                                                                           
digicampipe/tests/test_zfits_event_source.py::test_and_benchmark_expert_event_source SKIPPED

**Comment by dneise** [comment]
yes .. these are skipped intentionally. The benchmarks take some seconds to run, which is annoying.

**Comment by dneise** [comment]
Okay, @calispac and me discussed this on the phone. 
We thought it is maybe best to let normal users execute the "quick tests" by default. And only execute "all tests" when astrometrey.net is installed. 

Travis is still executing all tests.

In #99 modified the README accordingly and wrote a pytest.ini which will execute only the quick tests by default.
